searchSpace:
   n_rotates:
      _type: choice
      _value: [4,5,6,7,8,9,10]
   n_scales:
      _type: choice
      _value: [4,5,6,7,8,9,10] 
   length_scale:
      _type: uniform
      _value: [1, 100]
   lr:
      _type: loguniform
      _value: [0.001, 0.5]
   act_dis:
      _type: uniform
      _value: [0.8, 1.0]
   state_dis:
      _type: uniform
      _value: [0.8, 1.0]
   active_prop:
      _type: uniform
      _value: [0.01, 0.5]
   epsilon:
      _type: uniform
      _value: [0.3, 0.6]
      
experimentName: EXPERIMENT
trialCommand: python exp_ratbox_hexssp.py
trialConcurrency: 4
maxTrialNumber: 200
maxExperimentDuration: 12h
tuner:
   name: Anneal
   classArgs:
      optimize_mode: maximize
trainingService:
   platform: local